### ISSUE TITLE
Rename this project

### ISSUE THREAD

**Issue by ewilligers** [WICG/raw-sockets#10]
The current name might be associated with [IPPROTO_RAW](https://stackoverflow.com/questions/24590818/what-is-the-difference-between-ipproto-ip-and-ipproto-raw) / [SOCK_RAW](https://stackoverflow.com/questions/30780082/sock-raw-option-in-socket-system-call), as documented in [https://linux.die.net/man/7/raw](https://linux.die.net/man/7/raw)

The name `native sockets` has been suggested.

**Comment by phoglenix** [comment]
We should avoid using "native" per https://developers.google.com/style/word-list#letter-n and it's also inaccurate because the sockets implementation is not the native (OS-level) one.
What about `low level sockets`?

**Comment by ewilligers** [comment]
Some words that indicate early, basic, fundamental, simplest elements, first principles:

- [classic](https://www.google.com/search?q=meaning+of+classic)
- [elementary](https://www.google.com/search?q=meaning+of+elementary)
- [primary](https://www.google.com/search?q=meaning+of+primary)
- [primitive](https://www.google.com/search?q=meaning+of+primitive)
- [rudimentary](https://www.google.com/search?q=meaning+of+rudimentary)

I think `elementary sockets` works.

**Comment by mfalken** [comment]
`direct sockets`?

**Comment by mgiuca** [comment]
"Elementary" is just a bit too long (written and spoken, with 5 syllables).

Synonyms for "raw" (meaning "frank and realistic in the depiction of unpleasant situations") include:

- realistic
- true to life
- unembellished
- unvarnished
- gritty
- naked
- bare
- brutal
- harsh
- frank
- candid
- honest
- forthright
- straightforward
- direct
- blunt
- outspoken
- warts and all

Perhaps "bare sockets" which kinda fits with accepted terminology of "[bare metal](https://en.wikipedia.org/wiki/Bare-metal_server)". They're "naked" as in not wrapped with other layers.

We could also go "real sockets" though that has positive connotations which we kinda want to avoid since this is for the dirty low-level stuff, not something we want to encourage everyone to use. "direct sockets".

**Comment by ewilligers** [comment]
> "Elementary" is just a bit too long

> Is... is there something wrong with "TCP and UDP sockets"?

"TCP and UDP sockets" is longer. It is also the name of the [earlier proposal](https://www.w3.org/TR/tcp-udp-sockets/), potentially allowing confusion.

**Comment by phoglenix** [comment]
I feel that "direct" isn't strongly meaningful in the name (to me it's much more strongly related to "fastest route" than to "raw" or "fundamental"). The main connection is the meaning of "without intermediaries" which is somewhat the correct implication to give.
Of the options floated, I think "bare" or "primitive" might be best.
